### ISSUE TITLE
After 10 epoches, it's down.

### ISSUE THREAD

**Issue by robotzheng** [HymEric/VSR-DUF-Reimplement#4]
valid cost :4 95 finished.
valid cost :4 96 finished.
valid cost :4 97 finished.
valid cost :4 98 finished.
valid cost :4 99 finished.
Epoch - 10, avg loss on train set: 0.0000811, avg loss on valid set: 0.0001108.
Traceback (most recent call last):
  File "mytrain.py", line 269, in <module>
    freeze_graph(check_point_folder='./checkpoint/',model_folder='./model',pb_name='My_Duf_'+str(global_step)+'.pb')
  File "mytrain.py", line 42, in freeze_graph
    input_graph_def = graph.as_graph_def()
  File "/usr/local/python3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3150, in as_graph_def
    result, _ = self._as_graph_def(from_version, add_shapes)
  File "/usr/local/python3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3108, in _as_graph_def
    c_api.TF_GraphToGraphDef(self._c_graph, buf)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot serialize protocol buffer of type tensorflow.GraphDef as the serialized size (2153065360bytes) would be larger than the limit (2147483647 bytes)

**Comment by HymEric** [comment]
This error probably is caused by your TF envirnment for freezing operation procedure if the other setting is all right.
Do your prepare the environment same with README
