### ISSUE TITLE
it does not work

### ISSUE THREAD

**Issue by ruyiluo** [HymEric/VSR-DUF-Reimplement#5]
Hello！
I prepared the needed environments you provide.
but when I run this code I encounter an error as follow

```
Traceback (most recent call last):
  File "/home/ryluo/anaconda3/envs/tf18/lib/python3.6/site-packages/numpy/lib/arraypad.py", line 935, in _normalize_shape
    shape_arr = np.broadcast_to(shape_arr, (ndims, 2))
  File "/home/ryluo/anaconda3/envs/tf18/lib/python3.6/site-packages/numpy/lib/stride_tricks.py", line 176, in broadcast_to
    return _broadcast_to(array, shape, subok=subok, readonly=True)
  File "/home/ryluo/anaconda3/envs/tf18/lib/python3.6/site-packages/numpy/lib/stride_tricks.py", line 128, in _broadcast_to
    op_flags=[op_flag], itershape=shape, order='C')
ValueError: operands could not be broadcast together with remapped shapes [original->remapped]: (4,2) and requested shape (1,2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mytrain.py", line 95, in <module>
    x_train_data,x_train_data_padded=get_x(x_train_path) # print(x_data_padded.shape) (26, 100, 115, 3)
  File "mytrain.py", line 78, in get_x
    frames_padded = np.lib.pad(frames, pad_width=((T_in // 2, T_in // 2), (0, 0), (0, 0), (0, 0)), mode='constant') # print(frames_padded.shape) (26, 100, 115, 3)
  File "/home/ryluo/anaconda3/envs/tf18/lib/python3.6/site-packages/numpy/lib/arraypad.py", line 1200, in pad
    pad_width = _validate_lengths(narray, pad_width)
  File "/home/ryluo/anaconda3/envs/tf18/lib/python3.6/site-packages/numpy/lib/arraypad.py", line 979, in _validate_lengths
    normshp = _normalize_shape(narray, number_elements)
  File "/home/ryluo/anaconda3/envs/tf18/lib/python3.6/site-packages/numpy/lib/arraypad.py", line 938, in _normalize_shape
    raise ValueError(fmt % (shape,))
ValueError: Unable to create correctly shaped tuple from ((3, 3), (0, 0), (0, 0), (0, 0))
```

Besides,
My data form is bmp.
Do you know how to solve this problem?

Thanks, 
ruyi

**Comment by HymEric** [comment]
Sorry I just do it for .png. But you can modify it in `mytrain.py` **line 70** for .bmp images.
